kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: autoscaling-virtuoso-internal
  namespace: ndc-dev
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: virtuoso-internal
    apiVersion: apps.openshift.io/v1
  minReplicas: 1
  maxReplicas: 2ß
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80