kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: dati-semantic-frontend
  namespace: ndc-prod
  labels:
    application: dati-semantic-frontend
spec:
  host: ndc-prod.apps.cloudpub.istat.it
  to:
    kind: Service
    name: dati-semantic-frontend
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None