apiVersion: v1
kind: Service
metadata:
  name: mysql-dev-external-service
  namespace: ndc-dev
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-dev-external-service
subsets:
  - addresses:
      - ip: 10.242.0.132
    ports:
      - port: 3306
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mysql-dev-external-service
  namespace: ndc-dev
  labels:
    application: mysql-dev-external-service
spec:
  to:
    kind: Service
    name: mysql-dev-external-service
    weight: 100
  port:
    targetPort: 3306
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None