kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: dati-semantic-backend
  namespace: ndc-dev
  labels:
    application: dati-semantic-backend
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: dati-semantic-backend
  template:
    metadata:
      name: dati-semantic-backend
      creationTimestamp: null
      labels:
        application: dati-semantic-backend
        deploymentConfig: dati-semantic-backend
    spec:
      containers:
        - resources:
            limits:
              cpu: 800m
              memory: 2048Mi
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dati-semantic-backend
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            ghcr.io/teamdigitale/dati-semantic-backend:20211216-210-4dff0e4
          env:
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: http://temporary-elasticsearch:9200
            - name: VIRTUOSO_SPARQL
              value: http://virtuoso-dev-external-service:8890/sparql-auth
            - name: VIRTUOSO_SPARQL_GRAPH_STORE
              value: http://virtuoso-dev-external-service:8890/sparql-graph-crud-auth
            - name: VIRTUOSO_USERNAME
              value: sv_ndc_virtuoso_app
            - name: VIRTUOSO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: virtuoso-sql
                  key: virtuoso-dev
            - name: HARVESTER_REPOSITORIES
              value: "https://github.com/ash1425/sample-ontology-repo"
            - name: NDC_BASE_URL
              value: https://ndc-dev.apps.cloudpub.testedev.istat.it/api
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db-testedev-mysql.mysql.database.azure.com:3306/sv_ndc_harvest?useSSL=true
            - name: SPRING_DATASOURCE_USERNAME
              value: sv_ndc_harvest_app
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-dev
                  name: mysql-dev
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
