name: updateConfig

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'service name'
        required: true
      imageWithNewTag:
        description: 'image with a tag'
        required: true

jobs:
  updateImage:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.15.1

      - name: run script
        run: ./updateImage.sh ${{ github.event.inputs.serviceName }} ${{ github.event.inputs.imageWithNewTag }}

      - name: Commit new config
        run: |
          git config --global user.name 'Github action user'
          git config --global user.email 'gh-actions-user@users.noreply.github.com'
          git add .
          git commit -m "Automated container image update for service ${{ github.event.inputs.serviceName }}"
          git push  
